version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: funchealth
    container_name: funchealth-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./var/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - funchealth
  nginx:
    image: nginx:alpine
    container_name: funchealth-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - funchealth

networks:
  funchealth:
    driver: bridge
